Remove 6th keyword from `xilem_web`. (#976)
Apparently 5 is the maximum.

```
error: failed to publish to registry at https://crates.io

Caused by:
  the remote server responded with an error (status 400 Bad Request): expected at most 5 keywords per crate
```